.PHONY: clean All

All:
	@echo "----------Building project:[ Pilas - Debug ]----------"
	@cd "Pilar" && "$(MAKE)" -f  "Pilas.mk"
clean:
	@echo "----------Cleaning project:[ Pilas - Debug ]----------"
	@cd "Pilar" && "$(MAKE)" -f  "Pilas.mk" clean
